name: Docker CI/CD → Render

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Docker Hub Login
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Extract commit SHA
        id: vars
        run: |
          echo "SHA=$(git rev-parse --short HEAD)" >> "$GITHUB_OUTPUT"

      - name: Debug SHA
        run: echo "🔖 Using tag: ${{ steps.vars.outputs.SHA }}"

      - name: Build Docker image
        run: |
          docker build --no-cache \
            --build-arg CACHEBUST=${{ steps.vars.outputs.SHA }} \
            -t ${{ secrets.DOCKER_USERNAME }}/ieee-wie-pwa:${{ steps.vars.outputs.SHA }} \
            -t ${{ secrets.DOCKER_USERNAME }}/ieee-wie-pwa:latest .

      - name: Push Docker images
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/ieee-wie-pwa:${{ steps.vars.outputs.SHA }}
          docker push ${{ secrets.DOCKER_USERNAME }}/ieee-wie-pwa:latest

      - name: Show image digest
        run: |
          docker inspect --format='📦 Digest: {{index .RepoDigests 0}}' ${{ secrets.DOCKER_USERNAME }}/ieee-wie-pwa:latest

      - name: Trigger Render redeploy
        run: |
          curl -s -X POST "https://api.render.com/v1/services/${{ secrets.RENDER_SERVICE_ID }}/deploys" \
            -H "Authorization: Bearer ${{ secrets.RENDER_API_KEY }}" \
            -H "Content-Type: application/json" \
            -d '{}' \
          && echo "🚀 Render redeploy triggered!"
